language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
before_install:
  - gem install bundler
install: gem install rails
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec --require spec_helper
